version: '3.9'

services:
  kube-launcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kube-launcher
    ports:
      - "8000:8000"
    environment:
      # Optional: override kube context (used in your app if you support it)
      KUBECONFIG: /root/.kube/config
    volumes:
      # Mount your local kubeconfig into container
      - ~/.kube:/root/.kube:ro
      - ~/.aws:/root/.aws # Uncomment this if you want to use EKS cluster
